--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1.pgdg120+1)
-- Dumped by pg_dump version 17.5

-- Started on 2025-08-18 02:20:42

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3364 (class 1262 OID 16384)
-- Name: chats; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE chats WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE chats OWNER TO postgres;

\connect chats

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16390)
-- Name: message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.message (
    message_uid bigint NOT NULL,
    mod_dt timestamp(6) without time zone,
    reg_dt timestamp(6) without time zone,
    content character varying(255) NOT NULL,
    receiver_id bigint NOT NULL,
    sender_id bigint NOT NULL
);


ALTER TABLE public.message OWNER TO postgres;

--
-- TOC entry 3365 (class 0 OID 0)
-- Dependencies: 218
-- Name: COLUMN message.mod_dt; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.message.mod_dt IS '업데이트 날짜 시간';


--
-- TOC entry 3366 (class 0 OID 0)
-- Dependencies: 218
-- Name: COLUMN message.reg_dt; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.message.reg_dt IS '등록 날짜 시간';


--
-- TOC entry 3367 (class 0 OID 0)
-- Dependencies: 218
-- Name: COLUMN message.content; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.message.content IS '메시지 본문';


--
-- TOC entry 3368 (class 0 OID 0)
-- Dependencies: 218
-- Name: COLUMN message.receiver_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.message.receiver_id IS '채팅 수신자';


--
-- TOC entry 3369 (class 0 OID 0)
-- Dependencies: 218
-- Name: COLUMN message.sender_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.message.sender_id IS '채팅 발신자';


--
-- TOC entry 217 (class 1259 OID 16389)
-- Name: message_message_uid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.message ALTER COLUMN message_uid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_message_uid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3358 (class 0 OID 16390)
-- Dependencies: 218
-- Data for Name: message; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.message (message_uid, mod_dt, reg_dt, content, receiver_id, sender_id) FROM stdin;
1	2025-08-11 15:04:01.392649	2025-08-11 15:04:01.392649	ㅎㅇㅎㅇ	4	5
2	2025-08-11 15:04:07.939793	2025-08-11 15:04:07.939793	하이요ㅋ	5	4
3	2025-08-12 06:12:00.436679	2025-08-12 06:12:00.436679	ㅎㅇ	6	4
4	2025-08-12 06:12:02.089926	2025-08-12 06:12:02.089926	ㅎㅇ	6	4
5	2025-08-12 06:12:03.268468	2025-08-12 06:12:03.268468	ㅎㅇ	6	4
6	2025-08-12 06:12:58.000968	2025-08-12 06:12:58.000968	gd	6	4
7	2025-08-12 06:14:34.819345	2025-08-12 06:14:34.819345	ㅎㅇ	5	4
8	2025-08-12 06:14:35.107981	2025-08-12 06:14:35.107981	ㅎㅇ	5	4
9	2025-08-12 06:14:35.318054	2025-08-12 06:14:35.318054	ㅎㅇ	5	4
10	2025-08-12 06:14:35.518897	2025-08-12 06:14:35.518897	ㅎㅇ	5	4
11	2025-08-12 06:14:35.716081	2025-08-12 06:14:35.716081	ㅎㅇ	5	4
12	2025-08-12 06:14:35.900684	2025-08-12 06:14:35.900684	ㅎㅇ	5	4
13	2025-08-12 06:14:36.079841	2025-08-12 06:14:36.079841	ㅎㅇ	5	4
14	2025-08-12 06:33:55.385342	2025-08-12 06:33:55.385342	h	5	5
15	2025-08-12 06:33:55.563895	2025-08-12 06:33:55.563895	h	5	5
16	2025-08-12 06:33:55.742151	2025-08-12 06:33:55.742151	h	5	5
17	2025-08-12 06:33:56.420368	2025-08-12 06:33:56.420368	hㅗ	5	5
18	2025-08-12 06:33:56.61351	2025-08-12 06:33:56.61351	ㅗ	5	5
19	2025-08-12 06:33:56.813601	2025-08-12 06:33:56.813601	ㅗ	5	5
20	2025-08-12 06:33:56.99892	2025-08-12 06:33:56.99892	ㅗ	5	5
21	2025-08-12 06:33:57.173883	2025-08-12 06:33:57.173883	ㅗ	5	5
22	2025-08-12 06:33:57.349097	2025-08-12 06:33:57.349097	ㅗ	5	5
23	2025-08-12 06:33:57.517005	2025-08-12 06:33:57.517005	ㅗ	5	5
24	2025-08-12 06:33:57.686348	2025-08-12 06:33:57.686348	ㅗ	5	5
25	2025-08-12 08:11:17.470154	2025-08-12 08:11:17.470154	gd	6	5
26	2025-08-12 08:11:19.948199	2025-08-12 08:11:19.948199	gd	6	5
27	2025-08-12 08:11:22.740337	2025-08-12 08:11:22.740337	ㅎㅇ	6	5
28	2025-08-12 08:11:42.896869	2025-08-12 08:11:42.896869	ㅎㅇ	6	5
29	2025-08-12 08:16:18.97377	2025-08-12 08:16:18.97377	ㅎㅇ	5	5
30	2025-08-12 08:16:21.443737	2025-08-12 08:16:21.443737	ㅎㅇ	5	5
31	2025-08-12 08:16:22.639402	2025-08-12 08:16:22.639402	ㅎㅇ	5	5
32	2025-08-12 08:20:14.854355	2025-08-12 08:20:14.854355	gd	5	5
33	2025-08-12 08:20:17.619186	2025-08-12 08:20:17.619186	아씹	5	5
34	2025-08-12 08:20:19.192335	2025-08-12 08:20:19.192335	왜 두번가냐ㅗㄱ	5	5
35	2025-08-12 08:20:21.562154	2025-08-12 08:20:21.562154	왜 오전8시냐고	5	5
36	2025-08-12 08:20:54.605281	2025-08-12 08:20:54.605281	ㅎㅇ	5	5
37	2025-08-12 08:24:57.764285	2025-08-12 08:24:57.764285	gd	5	5
38	2025-08-12 08:24:59.299713	2025-08-12 08:24:59.299713	ㅎㅇ	5	5
39	2025-08-12 08:25:22.494032	2025-08-12 08:25:22.494032	ㅎㅇ	5	5
40	2025-08-12 08:28:34.335417	2025-08-12 08:28:34.335417	ㅎㅇ	5	5
41	2025-08-12 08:28:36.801846	2025-08-12 08:28:36.801846	ㅇㅎ	5	5
42	2025-08-12 08:28:38.532938	2025-08-12 08:28:38.532938	ㅁㄴㅇㄹ	5	5
43	2025-08-12 08:29:15.839524	2025-08-12 08:29:15.839524	ㅎㅇ	5	5
44	2025-08-12 08:32:35.253636	2025-08-12 08:32:35.253636	ㅎㅇ요	6	4
45	2025-08-12 08:32:44.602317	2025-08-12 08:32:44.602317	ㅎㅇㅎㅇ	4	4
46	2025-08-12 08:38:28.977438	2025-08-12 08:38:28.977438	ㅇ	4	4
47	2025-08-12 08:39:27.467189	2025-08-12 08:39:27.467189	ㅎㅇ	6	4
48	2025-08-12 08:56:33.53891	2025-08-12 08:56:33.53891	ㅇㅀ	6	4
49	2025-08-12 10:22:31.944676	2025-08-12 10:22:31.944676	gd	5	5
50	2025-08-12 10:22:32.394347	2025-08-12 10:22:32.394347	gd	5	5
51	2025-08-13 06:15:48.193657	2025-08-13 06:15:48.193657	tgd	5	5
52	2025-08-13 06:15:51.112446	2025-08-13 06:15:51.112446	ㅎㅇ	5	5
53	2025-08-13 06:15:57.072264	2025-08-13 06:15:57.072264	ㅎㅇ	6	5
54	2025-08-13 13:26:34.224217	2025-08-13 13:26:34.224217	jk	3	2
55	2025-08-13 13:26:41.513585	2025-08-13 13:26:41.513585	lklkjlkjlk	3	2
56	2025-08-13 13:27:07.965166	2025-08-13 13:27:07.965166	kjlkjlkjlkjlkjlkj	3	2
57	2025-08-13 13:27:10.838699	2025-08-13 13:27:10.838699	??	2	3
58	2025-08-13 13:27:14.675272	2025-08-13 13:27:14.675272	??????	3	2
59	2025-08-13 13:27:18.205034	2025-08-13 13:27:18.205034	소켓	2	3
60	2025-08-13 14:32:03.932465	2025-08-13 14:32:03.932465	안녕하세요	1	1
61	2025-08-13 14:32:09.08379	2025-08-13 14:32:09.08379	안녕하세요	1	1
62	2025-08-13 14:32:16.005467	2025-08-13 14:32:16.005467	ㅇㅇㅇㅇㅇ	1	1
63	2025-08-13 14:33:57.17659	2025-08-13 14:33:57.17659	안녕	6	1
64	2025-08-13 14:34:30.488706	2025-08-13 14:34:30.488706	하이하이	1	6
65	2025-08-13 23:55:43.939487	2025-08-13 23:55:43.939487	ㅎㅇ	4	5
66	2025-08-13 23:55:54.84836	2025-08-13 23:55:54.84836	ㅎㅇ	5	4
67	2025-08-14 00:20:21.016467	2025-08-14 00:20:21.016467	??	5	2
68	2025-08-14 00:20:36.288771	2025-08-14 00:20:36.288771	온라인인데	5	2
69	2025-08-14 00:20:46.487187	2025-08-14 00:20:46.487187	누가 흑염소야	5	2
70	2025-08-14 00:21:32.566318	2025-08-14 00:21:32.566318	???	3	2
71	2025-08-14 01:14:56.924451	2025-08-14 01:14:56.924451	안녕	5	1
72	2025-08-14 05:05:04.187275	2025-08-14 05:05:04.187275	메세지가 보이면 당근을 흔들어 주세요	5	3
73	2025-08-14 05:07:50.903331	2025-08-14 05:07:50.903331	??	5	3
74	2025-08-15 06:02:20.034569	2025-08-15 06:02:20.034569	djdl	2	3
75	2025-08-15 07:22:21.056425	2025-08-15 07:22:21.056425	메세지 가나요?	6	3
80	2025-08-17 16:23:56.062319	2025-08-17 16:23:56.062319	안녀아헤셔	14	13
81	2025-08-17 16:23:56.068257	2025-08-17 16:23:56.068257	셔	14	13
82	2025-08-17 16:24:01.348432	2025-08-17 16:24:01.348432	안	14	13
83	2025-08-17 16:24:01.35414	2025-08-17 16:24:01.35414	안	14	13
\.


--
-- TOC entry 3370 (class 0 OID 0)
-- Dependencies: 217
-- Name: message_message_uid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.message_message_uid_seq', 83, true);


--
-- TOC entry 3211 (class 2606 OID 16394)
-- Name: message message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT message_pkey PRIMARY KEY (message_uid);


-- Completed on 2025-08-18 02:20:43

--
-- PostgreSQL database dump complete
--

