# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_services/object_detect/object_detect.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai_services/object_detect/object_detect.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-ai_services/object_detect/object_detect.proto\x12\robject_detect\"%\n\rDetectRequest\x12\x14\n\x0cimage_base64\x18\x01 \x01(\t\"*\n\x0e\x44\x65tectResponse\x12\x18\n\x10\x64\x65tected_objects\x18\x01 \x03(\t2\\\n\x13ObjectDetectService\x12\x45\n\x06\x44\x65tect\x12\x1c.object_detect.DetectRequest\x1a\x1d.object_detect.DetectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_services.object_detect.object_detect_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTREQUEST']._serialized_start=64
  _globals['_DETECTREQUEST']._serialized_end=101
  _globals['_DETECTRESPONSE']._serialized_start=103
  _globals['_DETECTRESPONSE']._serialized_end=145
  _globals['_OBJECTDETECTSERVICE']._serialized_start=147
  _globals['_OBJECTDETECTSERVICE']._serialized_end=239
# @@protoc_insertion_point(module_scope)
